name = "LasIO"
uuid = "570499db-eae3-5eb6-bdd5-a5326f375e68"
keywords = ["LAS", "lidar", "IO"]
license = "MIT"
desc = "Read and write LAS lidar point cloud files"
version = "0.3.7"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
ColorTypes = "0.7, 0.8, 0.9, 0.10, 0.11"
FileIO = "1"
FixedPointNumbers = "0.5, 0.6, 0.7, 0.8"
GeometryTypes = "0.6, 0.7, 0.8"
julia = "1"

[extras]
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Mmap"]
